quiet: False
dir: mocks/{{ replaceAll .InterfaceDirRelative "internal" "internal_" }}
disable-version-string: True
mockname: "{{.InterfaceName}}"
outpkg: "{{.PackageName}}"
filename: "{{.InterfaceName}}.go"
packages:
    github.com/arfan21/shopifyx-api/internal/domain:
        interfaces:
