basePath: /
definitions:
  github_com_arfan21_project-sprint-shopifyx-api_internal_model.ProductGetResponse:
    properties:
      condition:
        type: string
      imageUrl:
        type: string
      isPurchaseable:
        type: boolean
      name:
        type: string
      price:
        type: number
      productId:
        type: string
      purchaseCount:
        type: integer
      stock:
        type: integer
      tags:
        items:
          type: string
        type: array
    type: object
  github_com_arfan21_project-sprint-shopifyx-api_internal_model.ProductRequest:
    properties:
      condition:
        enum:
        - new
        - second
        type: string
      imageUrl:
        type: string
      isPurchaseable:
        type: boolean
      name:
        maxLength: 60
        minLength: 5
        type: string
      price:
        type: number
      stock:
        type: integer
      tags:
        items:
          type: string
        type: array
    required:
    - condition
    - imageUrl
    - isPurchaseable
    - name
    - price
    - stock
    type: object
  github_com_arfan21_project-sprint-shopifyx-api_internal_model.UserLoginRequest:
    properties:
      password:
        maxLength: 15
        minLength: 5
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  github_com_arfan21_project-sprint-shopifyx-api_internal_model.UserLoginResponse:
    properties:
      accessToken:
        type: string
      name:
        type: string
      username:
        type: string
    type: object
  github_com_arfan21_project-sprint-shopifyx-api_internal_model.UserRegisterRequest:
    properties:
      name:
        maxLength: 50
        minLength: 5
        type: string
      password:
        maxLength: 15
        minLength: 5
        type: string
      username:
        type: string
    required:
    - name
    - password
    - username
    type: object
  github_com_arfan21_project-sprint-shopifyx-api_pkg_pkgutil.ErrValidationResponse:
    properties:
      field:
        type: string
      message:
        type: string
    type: object
  github_com_arfan21_project-sprint-shopifyx-api_pkg_pkgutil.HTTPResponse:
    properties:
      data: {}
      message:
        example: Success
        type: string
      meta: {}
    type: object
host: localhost:8080
info:
  contact:
    name: API Support
    url: http://www.synapsis.id
  description: This is a sample server cell for project-sprint-shopifyx-api.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: project-sprint-shopifyx-api
  version: "1.0"
paths:
  /v1/product:
    get:
      consumes:
      - application/json
      description: Get product list
      parameters:
      - description: With the bearer started
        in: header
        name: Authorization
        required: true
        type: string
      - description: Get product list by user
        in: query
        name: userOnly
        type: boolean
      - description: Limit
        in: query
        name: limit
        type: integer
      - description: Offset
        in: query
        name: offset
        type: integer
      - description: Condition
        in: query
        name: condition
        type: string
      - description: Tags
        in: query
        name: tags
        type: string
      - description: Show empty stock
        in: query
        name: showEmptyStock
        type: boolean
      - description: Max price
        in: query
        name: maxPrice
        type: number
      - description: Min price
        in: query
        name: minPrice
        type: number
      - description: Sort by
        in: query
        name: sortBy
        type: string
      - description: Order by
        in: query
        name: orderBy
        type: string
      - description: Search
        in: query
        name: search
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/github_com_arfan21_project-sprint-shopifyx-api_pkg_pkgutil.HTTPResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/github_com_arfan21_project-sprint-shopifyx-api_internal_model.ProductGetResponse'
                  type: array
              type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_arfan21_project-sprint-shopifyx-api_pkg_pkgutil.HTTPResponse'
      summary: Get product list
      tags:
      - product
    post:
      consumes:
      - application/json
      description: Create product
      parameters:
      - description: With the bearer started
        in: header
        name: Authorization
        required: true
        type: string
      - description: Payload product create request
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/github_com_arfan21_project-sprint-shopifyx-api_internal_model.ProductRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_arfan21_project-sprint-shopifyx-api_pkg_pkgutil.HTTPResponse'
        "400":
          description: Error validation field
          schema:
            allOf:
            - $ref: '#/definitions/github_com_arfan21_project-sprint-shopifyx-api_pkg_pkgutil.HTTPResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/github_com_arfan21_project-sprint-shopifyx-api_pkg_pkgutil.ErrValidationResponse'
                  type: array
              type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_arfan21_project-sprint-shopifyx-api_pkg_pkgutil.HTTPResponse'
      summary: Create product
      tags:
      - product
  /v1/product/{id}:
    delete:
      consumes:
      - application/json
      description: Delete product
      parameters:
      - description: With the bearer started
        in: header
        name: Authorization
        required: true
        type: string
      - description: Product ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_arfan21_project-sprint-shopifyx-api_pkg_pkgutil.HTTPResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_arfan21_project-sprint-shopifyx-api_pkg_pkgutil.HTTPResponse'
      summary: Delete product
      tags:
      - product
    patch:
      consumes:
      - application/json
      description: Update product
      parameters:
      - description: With the bearer started
        in: header
        name: Authorization
        required: true
        type: string
      - description: Payload product update request
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/github_com_arfan21_project-sprint-shopifyx-api_internal_model.ProductRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_arfan21_project-sprint-shopifyx-api_pkg_pkgutil.HTTPResponse'
        "400":
          description: Error validation field
          schema:
            allOf:
            - $ref: '#/definitions/github_com_arfan21_project-sprint-shopifyx-api_pkg_pkgutil.HTTPResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/github_com_arfan21_project-sprint-shopifyx-api_pkg_pkgutil.ErrValidationResponse'
                  type: array
              type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_arfan21_project-sprint-shopifyx-api_pkg_pkgutil.HTTPResponse'
      summary: Update product
      tags:
      - product
  /v1/user/login:
    post:
      consumes:
      - application/json
      description: Login user
      parameters:
      - description: Payload user Login Request
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/github_com_arfan21_project-sprint-shopifyx-api_internal_model.UserLoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/github_com_arfan21_project-sprint-shopifyx-api_pkg_pkgutil.HTTPResponse'
            - properties:
                data:
                  $ref: '#/definitions/github_com_arfan21_project-sprint-shopifyx-api_internal_model.UserLoginResponse'
              type: object
        "400":
          description: Error validation field
          schema:
            allOf:
            - $ref: '#/definitions/github_com_arfan21_project-sprint-shopifyx-api_pkg_pkgutil.HTTPResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/github_com_arfan21_project-sprint-shopifyx-api_pkg_pkgutil.ErrValidationResponse'
                  type: array
              type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_arfan21_project-sprint-shopifyx-api_pkg_pkgutil.HTTPResponse'
      summary: Login user
      tags:
      - user
  /v1/user/register:
    post:
      consumes:
      - application/json
      description: Register user
      parameters:
      - description: Payload user Register Request
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/github_com_arfan21_project-sprint-shopifyx-api_internal_model.UserRegisterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            allOf:
            - $ref: '#/definitions/github_com_arfan21_project-sprint-shopifyx-api_pkg_pkgutil.HTTPResponse'
            - properties:
                data:
                  $ref: '#/definitions/github_com_arfan21_project-sprint-shopifyx-api_internal_model.UserLoginResponse'
              type: object
        "400":
          description: Error validation field
          schema:
            allOf:
            - $ref: '#/definitions/github_com_arfan21_project-sprint-shopifyx-api_pkg_pkgutil.HTTPResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/github_com_arfan21_project-sprint-shopifyx-api_pkg_pkgutil.ErrValidationResponse'
                  type: array
              type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_arfan21_project-sprint-shopifyx-api_pkg_pkgutil.HTTPResponse'
      summary: Register user
      tags:
      - user
swagger: "2.0"
